FROM jobs-tests-base

ENV PYTHONDONTWRITEBYTECODE 1

# base image has set USER to coreapi and requirements installation then fails
USER root
COPY . /f8a_jobs
ADD ./.git /.git
RUN cd /f8a_jobs/tests && pip3 install -r ./requirements.txt

# This is needed for codecov so the CWD is writeable and codecov can write stats to a file.
WORKDIR /tmp

CMD ["py.test"]
