swagger: "2.0"
info:
  title: API for Bayesian Core Jobs
  version: "0.1"
basePath: "/api/v1/"
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  auth_token:
    type: "apiKey"
    name: "auth-token"
    in: "header"

paths:
  /generate-token:
    get:
      tags: [Authentication]
      operationId: bayesian_jobs.api_v1.generate_token
      summary: Get authentization token for communicationg with this service
      responses:
        200:
          description: Authentization token
        401:
          description: No suitable permissions
  /logout:
    get:
      tags: [Authentication]
      operationId: bayesian_jobs.api_v1.logout
      summary: Clean session
      responses:
        201:
          description: Successfully logged out
  /authorized:
    get:
      tags: [Authentication]
      operationId: bayesian_jobs.api_v1.authorized
      summary: Authentication redirection
      responses:
        200:
          description: Successfully authorized
  /liveness:
    get:
      tags: [Service settings]
      operationId: bayesian_jobs.api_v1.get_liveness
      summary: Get job service liveness
      responses:
        200:
          description: Service is alive
  /readiness:
    get:
      tags: [Service settings]
      operationId: bayesian_jobs.api_v1.get_readiness
      summary: Get job service readiness
      responses:
        200:
          description: Service is ready
  /service/state:
    get:
      tags: [Service settings]
      operationId: bayesian_jobs.api_v1.get_service_state
      summary: Get job service state
      security:
        - auth_token: []
      responses:
        200:
          description: State of the job service
    put:
      tags: [Service settings]
      operationId: bayesian_jobs.api_v1.put_service_state
      summary: Pause or resume job execution
      parameters:
        - $ref: "#/parameters/state"
      security:
        - auth_token: []
      responses:
        201:
          description: Information about job execution
  /jobs:
    get:
      tags: [Jobs options]
      operationId: bayesian_jobs.api_v1.get_jobs
      summary: Get all pending jobs
      parameters:
        - $ref: "#/parameters/job_type"
      security:
        - auth_token: []
      responses:
        200:
          description: All active jobs
  '/jobs/{job_id}':
    delete:
       tags: [Jobs options]
       operationId: bayesian_jobs.api_v1.delete_jobs
       summary: Delete a job
       parameters:
        - $ref: "#/parameters/job_id_path"
       security:
        - auth_token: []
       responses:
         201:
           description: Job with the given id was removed
    put:
      tags: [Jobs options]
      operationId: bayesian_jobs.api_v1.put_jobs
      summary: Jobs state manipulation
      parameters:
        - $ref: "#/parameters/job_id_path"
        - $ref: "#/parameters/state"
      security:
        - auth_token: []
      responses:
        201:
          description: New analyses job scheduled
  '/jobs/clean-failed':
    delete:
       tags: [Jobs options]
       operationId: bayesian_jobs.api_v1.delete_clean_failed
       summary: Delete all failed jobs
       security:
         - auth_token: []
       responses:
         201:
           description: All failed jobs were deleted
         401:
           description: Error describing issue in your SQL query or error on querying
  '/debug/show-select-query':
    post:
       tags: [Debug]
       operationId: bayesian_jobs.api_v1.post_show_select_query
       summary: Show SQL query that will be used in case of filter parametrized jobs
       parameters:
        - name: filter_definition
          in: body
          required: true
          description: JSON describing SQL query
          schema:
            $ref: "#/definitions/Filter"
       security:
        - auth_token: []
       responses:
         200:
           description: Constructed SQL query for the given filter definition
         401:
           description: Error describing issue in your SQL query
  '/debug/expand-filter-query':
    post:
       tags: [Debug]
       operationId: bayesian_jobs.api_v1.post_expand_filter_query
       summary: Use filter to query database and show results that matched given filter
       parameters:
        - name: filter_definition
          in: body
          required: true
          description: JSON describing SQL query
          schema:
            $ref: "#/definitions/Filter"
       security:
        - auth_token: []
       responses:
         200:
           description: Matched records in database for the given filter definition
  '/jobs/flow-scheduling':
    post:
      tags: [Add new jobs]
      operationId: bayesian_jobs.api_v1.post_flow_scheduling
      summary: Schedule a new job for analyses
      parameters:
        - $ref: "#/parameters/job_id"
        - $ref: "#/parameters/periodically"
        - $ref: "#/parameters/when"
        - $ref: "#/parameters/misfire_grace_time"
        - $ref: "#/parameters/state"
        - name: kwargs
          in: body
          required: false
          description: Job keyword arguments for analyses scheduling
          schema:
            $ref: "#/definitions/FlowKwargs"
      security:
        - auth_token: []
      responses:
        201:
          description: New analyses job scheduled
  '/jobs/selective-flow-scheduling':
    post:
      tags: [Add new jobs]
      operationId: bayesian_jobs.api_v1.post_selective_flow_scheduling
      summary: Schedule a new job for analyses only with selected tasks marked for execution
      parameters:
        - $ref: "#/parameters/job_id"
        - $ref: "#/parameters/periodically"
        - $ref: "#/parameters/when"
        - $ref: "#/parameters/misfire_grace_time"
        - $ref: "#/parameters/state"
        - name: kwargs
          in: body
          required: false
          description: Job keyword arguments for selective analyses scheduling
          schema:
            $ref: "#/definitions/SelectiveKwargs"
      security:
        - auth_token: []
      responses:
        201:
          description: New analyses job scheduled
  '/jobs/popular-analyses':
    post:
      tags: [Add new jobs]
      operationId: bayesian_jobs.api_v1.post_popular_analyses
      summary: Analyse TOP packages
      parameters:
        - $ref: "#/parameters/job_id"
        - $ref: "#/parameters/periodically"
        - $ref: "#/parameters/when"
        - $ref: "#/parameters/misfire_grace_time"
        - $ref: "#/parameters/state"
        - $ref: "#/parameters/ecosystem"
        - $ref: "#/parameters/count"
        - $ref: "#/parameters/nversions"
        - $ref: "#/parameters/force"
      security:
        - auth_token: []
      responses:
        201:
          description: New analyses job scheduled
  '/jobs/clean-postgres':
    post:
      tags: [Add new jobs]
      operationId: bayesian_jobs.api_v1.post_clean_postgres
      summary: Analyse TOP packages
      parameters:
        - $ref: "#/parameters/job_id"
        - $ref: "#/parameters/periodically"
        - $ref: "#/parameters/when"
        - $ref: "#/parameters/misfire_grace_time"
        - $ref: "#/parameters/state"
      security:
        - auth_token: []
      responses:
        201:
          description: New analyses job scheduled
  '/jobs/sync-to-graph':
    post:
      tags: [Add new jobs]
      operationId: bayesian_jobs.api_v1.post_sync_to_graph
      summary: Sync all finished analyses to graph
      parameters:
        - $ref: "#/parameters/job_id"
        - $ref: "#/parameters/periodically"
        - $ref: "#/parameters/when"
        - $ref: "#/parameters/misfire_grace_time"
        - $ref: "#/parameters/state"
        - $ref: "#/parameters/start"
        - $ref: "#/parameters/end"
      security:
        - auth_token: []
      responses:
        201:
          description: Sync to graph scheduled

parameters:
  job_id_path:
    name: job_id
    in: path
    required: true
    description: Job identifier
    type: string
  job_id:
    name: job_id
    in: query
    required: false
    description: Job identifier
    type: string
  periodically:
    name: periodically
    in: query
    type: string
    required: false
    description: Set periodical job execution
  when:
    name: when
    in: query
    type: string
    required: false
    description: Date time in UTC when the job run should be scheduled
  misfire_grace_time:
    name: misfire_grace_time
    in: query
    type: string
    required: false
    description: Time how much job’s execution is allowed to be late before throwing away
  state:
    name: state
    in: query
    required: true
    description: State
    type: string
    items:
      type: string
    enum:
      - paused
      - running
  job_type:
     name: job_type
     in: query
     required: false
     description: Job specific listing
     type: string
     items:
       type: string
     enum:
       - all
       - failed
       - user
  ecosystem:
     name: ecosystem
     in: query
     required: true
     description: Ecosystem
     type: string
     items:
       type: string
     enum:
       - maven
       - npm
       - python
  count:
    name: count
    in: query
    required: false
    description: Number (or dash-separated range) of items
    type: string
  nversions:
    name: nversions
    in: query
    required: false
    description: Number of versions of each item
    type: integer
  force:
    name: force
    in: query
    required: false
    description: Force analyses scheduling
    type: boolean
    default: false
  start:
    name: start
    in: query
    required: false
    description: Analysis id to start syncing at
    type: integer
  end:
    name: end
    in: query
    required: false
    description: Analysis id to end syncing at
    type: integer

definitions:
  FlowKwargs:
    type: object
    required:
      - flow_name
      - flow_arguments
    properties:
      flow_name: &flow_name_analysis
        type: string
        description: Selinon flow that should be run
        example: "bayesianFlow"
      flow_arguments: &flow_arguments
        type: array
        description: List of arguments that should be supplied per flow
        items:
          $ref: "#/definitions/Any"
        example:
          - ecosystem: "npm"
            name: "serve-static"
            version: "1.7.1"
            force: true
          - ecosystem: "maven"
            name: "net.iharder:base64"
            version: "2.3.9"
            force: true
  SelectiveKwargs:
    type: object
    required:
      - flow_name
      - task_names
      - flow_arguments
    properties:
      flow_name:
        <<: *flow_name_analysis
      task_names: &task_names
        type: array
        description: A list of tasks that should be run
        items:
          type: string
        example:
          - "github_details"
          - "ResultCollector"
      flow_arguments:
        <<: *flow_arguments
      run_subsequent:
        type: boolean
        description: Run nodes that are dependent on tasks listed in task_names
        example: false
  Filter:
    type: object
    required:
      - '$filter'
    additionalProperties: true
    properties:
      '$filter':
        type: object
        required:
          - table
        additionalProperties: true
        properties:
          table:
            type: string
            description: table to which the given query should be applied
            example: "versions"
          joins:
            type: array
            description: List of joins that should be applied (defaults to NATURAL JOIN)
            items:
              $ref: "#/definitions/Any"
            example:
              - table: "packages"
                'on':
                  versions.package_id: "packages.id"
              - table: "ecosystems"
                'on':
                  ecosystems.id: "packages.ecosystem_id"
          where:
            type: object
            description: WHERE clause that should be applied
            example:
              packages.name: "serve-static"
          select:
            type: array
            description: SELECT filtering
            items:
              type: string
            example:
              - "packages.name as name"
              - "ecosystems.name as ecosystem"
              - "versions.identifier as version"

  Any:
    type: object
    additionalProperties: true
