apiVersion: v1
kind: Template
labels:
  template: bayesian-jobs
metadata:
  name: bayesian-jobs
  annotations:
    description: bayesian-jobs
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: bayesian-jobs
    name: bayesian-jobs
  spec:
    replicas: 1
    selector:
      service: bayesian-jobs
    template:
      metadata:
        labels:
          service: bayesian-jobs
      spec:
        containers:
        - env:
          - name: DEPLOYMENT_PREFIX
            valueFrom:
              configMapKeyRef:
                name: bayesian-config
                key: deployment-prefix
          - name: WORKER_ADMINISTRATION_REGION
            value: "api"
          - name: AWS_SQS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws
                key: sqs-access-key-id
          - name: AWS_SQS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: sqs-secret-access-key
          - name: AWS_S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
               name: aws
               key: s3-access-key-id
          - name: AWS_S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: s3-secret-access-key
          - name: BAYESIAN_SYNC_S3
            valueFrom:
              secretKeyRef:
                name: aws
                key: sync-s3
          - name: GITHUB_CONSUMER_KEY
            valueFrom:
              secretKeyRef:
                name: jobs
                key: github-oauth-consumer-key
          - name: GITHUB_CONSUMER_SECRET
            valueFrom:
              secretKeyRef:
                name: jobs
                key: github-oauth-consumer-secret
          - name: APP_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: jobs
                key: flask-app-secret-key
          #- name: GITHUB_ACCESS_TOKEN
          #  valueFrom:
          #    secretKeyRef:
          #      name: jobs
          #      key: github-access-token
          # this won't get used if running with SQS
          - name: RABBITMQ_SERVICE_SERVICE_HOST
            value: bayesian-broker
          - name: PGBOUNCER_SERVICE_HOST
            value: bayesian-pgbouncer
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: database
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: username
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: password
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          name: bayesian-jobs
          ports:
            - containerPort: 34000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/v1/readiness
              port: 34000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /api/v1/liveness
              port: 34000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 6
          resources:
            limits:
              memory: "512Mi"
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: bayesian-jobs
    name: bayesian-jobs
  spec:
    ports:
    - name: "34000"
      port: 34000
      protocol: TCP
      targetPort: 34000
    selector:
      service: bayesian-jobs
- apiVersion: v1
  kind: Route
  metadata:
    name: bayesian-jobs
  spec:
    host: ${BAYESIAN_JOBS_HOSTNAME}
    to:
      kind: Service
      name: bayesian-jobs

parameters:
- description: A hostname where the Bayesian Jobs should be exposed (will be auto-generated if empty)
  displayName: Bayesian Jobs hostname
  required: false
  name: BAYESIAN_JOBS_HOSTNAME

- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "registry.devshift.net"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "bayesian/coreapi-jobs"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"  # image-tag
