openapi: 3.0.1
info:
  title: Collection of APIs for backend processes
  version: '0.1'
paths:
  /ingestions/epv:
    post:
      tags:
      - Ingestion Process
      description: API to trigger a Selinon flow for ingestion of provided EPV.
      operationId: f8a_jobs.graph_ingestion.ingest_epv

      parameters:
      - name: auth-token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string

      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestPackageDetailsEPV"

      responses:
        201:
          description: Response with Selinon dispacher ID.
          content:
            application/json:
              schema:
                oneOf:
                - $ref: "#/components/schemas/ResponsePackageErrorDetails"
                - $ref: "#/components/schemas/ResponsePackageDetails"

        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Failed to initiate worker flow.

  /ingestions/epv-selective:
    post:
      tags:
      - Ingestion Process
      description: API to trigger a Selinon partial flow for ingestion of provided EPV.
      operationId: f8a_jobs.graph_ingestion.ingest_selective_epv

      parameters:
      - name: auth-token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string

      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestPackageDetailsSelctiveEPV"

      responses:
        201:
          description: Response with Selinon dispacher ID.
          content:
            application/json:
              schema:
                oneOf:
                - $ref: "#/components/schemas/ResponsePackageErrorDetails"
                - $ref: "#/components/schemas/ResponsePackageDetails"

        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Failed to initiate worker flow.

  /internal/ingestions/epv:
    post:
      tags:
        - Ingestion Process
      description: Internal API to trigger a Selinon flow for ingestion of provided EPV.
      operationId: f8a_jobs.graph_ingestion.ingest_epv_internal

      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestPackageDetailsEPV"

      responses:
        201:
          description: Response with Selinon dispacher ID.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ResponsePackageErrorDetails"
                  - $ref: "#/components/schemas/ResponsePackageDetails"

        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Failed to initiate worker flow.

  /internal/ingestions/epv-selective:
    post:
      tags:
        - Ingestion Process
      description: Internal API to trigger a Selinon partial flow for ingestion of provided EPV.
      operationId: f8a_jobs.graph_ingestion.ingest_selective_epv_internal

      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestPackageDetailsSelctiveEPV"

      responses:
        201:
          description: Response with Selinon dispacher ID.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ResponsePackageErrorDetails"
                  - $ref: "#/components/schemas/ResponsePackageDetails"

        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Failed to initiate worker flow.

  /internal/ingestions/component-bookkeeping:
    post:
      tags:
        - Ingestion Process
      description: >-
        Internal API to trigger a Selinon flow for storing data from api calls.
      operationId: f8a_jobs.bookkeeping.component_bookkeeping
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: Response with Selinon dispacher ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Incorrect data sent.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Failed to initiate worker flow.

components:
  schemas:
    Ecosystem:
      title: Ecosystem
      description: List of supported package ecosystems
      type: string
      enum:
        - maven
        - pypi
        - npm
        - golang
      example: maven

    Flows:
      title: Flow Name
      description: List of Selinon worker flow names
      type: string
      enum:
        - osioAnalysisFlow
        - bayesianFlow
        - bayesianApiFlow
        - bayesianPriorityFlow
        - bayesianAnalysisFlow
        - livenessFlow
        - bayesianPackageFlow
        - bayesianApiPackageFlow
        - bayesianPriorityPackageFlow
        - bayesianPackageAnalysisFlow
        - componentApiFlow
        - dependencyIngestFlow
        - osioUserNotificationFlow
        - gitOperationsFlow
        - golangCVEPredictionsFlow
        - newPackageFlow
        - newPackageAnalysisFlow
      example: bayesianFlow

    Source:
      title: Source
      description: List of alias of consumers
      type: string
      enum:
        - api
        - git-refresh
        - report
        - monitor
      example: api

    ResponsePackageDetails:
      title: API Response Body
      description: If request is procesed successfully, Selinon dispacher ID will be sent back.
      type: object
      properties:
        ecosystem:
          $ref: '#/components/schemas/Ecosystem'
        packages:
          type: array
          items:
            type: object
            properties:
                package:
                  type: string
                  example: org.json
                version:
                  type: string
                  example: 20201115
                dispacher_id:
                  type: string
                  example: a4e397bf-c55a-4fdf-86f8-cd8f71b9256d

    ResponsePackageErrorDetails:
      title: API Error Response Body
      description: If request json data is not in desired format, error will be thrown.
      type: object
      properties:
        ecosystem:
          $ref: '#/components/schemas/Ecosystem'
        packages:
          type: array
          items:
            type: object
            properties:
                pkg:
                  type: string
                  example: org.json
                ver:
                  type: string
                  example: 20201115
                error_message:
                  type: string
                  example: Incorrect data sent.

    RequestPackageDetailsEPV:
      title: API Request Body
      description: Request JSON where few keys are mandatory and few are optional.
      type: object
      required:
        - ecosystem
        - packages
      properties:
        ecosystem:
          $ref: '#/components/schemas/Ecosystem'
        packages:
          type: array
          items:
            type: object
            required:
              - package
              - version
            properties:
                package:
                  type: string
                  example: org.json
                version:
                  type: string
                  example: 20201115
        force:
          type: boolean
          example: false
        force_graph_sync:
          type: boolean
          example: true
        recursive_limit:
          type: integer
          example: 0
        flow_name:
          $ref: '#/components/schemas/Flows'
        source:
          $ref: '#/components/schemas/Source'

    RequestPackageDetailsSelctiveEPV:
      title: Selective API Request Body
      description: Request JSON where few keys are mandatory and few are optional.
      type: object
      required:
        - ecosystem
        - packages
        - task_names
      properties:
        ecosystem:
          $ref: '#/components/schemas/Ecosystem'
        packages:
          type: array
          items:
            type: object
            required:
              - package
            properties:
                package:
                  type: string
                  example: org.json
                version:
                  type: string
                  example: 20201115
        flow_name:
          $ref: '#/components/schemas/Flows'
        task_names:
          type: array
          items:
            type: string
          example: [
            'github_details',
            'PackageFinalizeTask',
            'PackageResultCollector',
            'PackageGraphImporterTask']
        follow_subflows:
          type: boolean
          example: True
        run_subsequent:
          type: boolean
          example: False
        force:
          type: boolean
          example: true
        source:
          $ref: '#/components/schemas/Source'