openapi: 3.0.1
info:
  title: Collection of APIs for backend processes
  version: "0.1"
paths:
  '/ingestions/epv':
    post:
      tags: [Ingestion Process]
      operationId: f8a_jobs.graph_ingestion.ingest_epv
      description: API to trigger a Selinon flow for ingestion of provided EPV.
      parameters:
        - name: auth-token
          in: header
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              '0':
                value: |-
                  {
                    "npm": [{
                        "package": "serve-static",
                        "version": "1.7.1"
                      }],
                    "maven":[{
                        "package": "net.iharder:base64",
                        "version": "2.3.9"
                      }]
                    }
              '1':
                value: |-
                  {
                    "npm": [{
                        "package": "esiglobal-components",
                        "version": "1.1.6"
                      }, {
                        "package": "@atmc/core",
                        "version": "0.1.16"
                      }],

                    "maven":[{
                        "pkg": "com.amazonaws:aws-java-sdk-sqs",
                        "ver": "1.11.825"
                      }, {
                        "pkg": "com.amazonaws:aws-java-sdk-dynamodb",
                        "ver": "1.11.825"
                      }],

                      "nuget": [{
                        "package": "microsoft.chakracore",
                        "version": "1.11.22"
                      }]
                    }
      responses:
        '201':
          description: Response with an array of Selinon dispacher IDs.
          content:
            application/json:
              schema:
                type: object
              examples:
                '0':
                  value: >
                    {
                      "maven": [
                          {
                              "dispacher_id": "75eeff32-23a5-405f-b83e-ef56155d8a4f",
                              "package": "net.iharder:base64",
                              "version": "2.3.9"
                          }
                      ],
                      "npm": [
                          {
                              "dispacher_id": "e36e9537-2c07-4817-adb1-f0169ac1105c",
                              "package": "serve-static",
                              "version": "1.7.1"
                          }
                      ]
                    }

                '1':
                   value: >
                    {
                        "maven": [
                            {
                                "error_message": "Incorrect data.",
                                "pkg": "com.amazonaws:aws-java-sdk-sqs",
                                "ver": "1.11.825"
                            },
                            {
                                "error_message": "Incorrect data.",
                                "pkg": "com.amazonaws:aws-java-sdk-dynamodb",
                                "ver": "1.11.825"
                            }
                        ],
                        "npm": [
                            {
                                "dispacher_id": "2d491fa9-9d53-4db8-8de0-df910e414442",
                                "package": "esiglobal-components",
                                "version": "1.1.6"
                            },
                            {
                                "dispacher_id": "e1355144-4638-4686-b023-c44a4a2ca334",
                                "package": "@atmc/core",
                                "version": "0.1.16"
                            }
                        ],
                        "nuget": [
                            {
                                "error_message": "Unsupported ecosystem."
                            }
                        ]
                    }

        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                '0':
                  value: >
                   {"detail": "The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
                   "status": 401,
                   "title": "Unauthorized",
                   "type": "about:blank"}

        '500':
          description: Internal Server Error
          content:
            application/json:
              examples:
                '0':
                  value: >
                    {"message":"Failed to initiate worker flow."}